# Generated by Django 5.1.3 on 2024-12-05 19:45

import django.core.validators
from django.db import migrations, models
import uuid
from datetime import timedelta

class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='video',
            name='id',
        ),
        migrations.AddField(
            model_name='video',
            name='video_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, null=True, serialize=False),
        ),
        migrations.AddField(
            model_name='video',
            name='video_length_time',
            field=models.DurationField(default=timedelta),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='video',
            name='thumbnail',
            field=models.FileField(upload_to='uploads/thumbnails', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['jpg', 'jpeg', 'png'])]),
        ),
        migrations.AlterField(
            model_name='video',
            name='video_file',
            field=models.FileField(upload_to='uploads/video_files', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'mov'])]),
        ),
    ]
