# Generated by Django 5.1.3 on 2024-12-05 19:52

from django.db import migrations
import uuid

def gen_uuid(apps, schema_editor):
    MyModel = apps.get_model("videos", "Video")
    for row in MyModel.objects.all():
        row.video_id = uuid.uuid4()
        row.save(update_fields=["video_id"])


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0002_remove_video_id_video_video_id_and_more'),
    ]
    

    operations = [
        migrations.RunPython(gen_uuid, reverse_code=migrations.RunPython.noop),
    ]
