# Generated by Django 5.1.3 on 2024-12-05 19:52

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('videos', '0003_auto_20241205_1952'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='video_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True, serialize=False),
        ),
    ]
